"""App entry point: build the rx.App and register the three routed pages.

All logic, styling, and UI live in sibling modules — this file is just
configuration so the framework can discover and mount the pages.
"""

import reflex as rx

from .pages.about import about
from .pages.catalogue import catalogue
from .pages.home import home

# Open Graph + Twitter Card metadata for link previews (iMessage, Slack,
# WhatsApp, Instagram DMs, Twitter, etc.). The og:image must be served at
# an absolute URL — Reflex serves /assets/* at the site root, so the
# 1200x630 preview generated by scripts/make_og_image.py is reachable at
# https://birdml.net/og-preview.jpg.
_OG_DESCRIPTION = (
    "Upload a bird photo and get instant species identification with a "
    "deep learning model trained on 525 species and 89,885 images."
)
_OG_IMAGE = "https://birdml.net/og-preview.jpg"


def _link_preview_meta(page_title: str) -> list[dict[str, str]]:
    """Build the og:* and twitter:* meta tags for a given page title."""
    return [
        {"property": "og:type", "content": "website"},
        {"property": "og:site_name", "content": "BirdML"},
        {"property": "og:title", "content": page_title},
        {"property": "og:description", "content": _OG_DESCRIPTION},
        {"property": "og:image", "content": _OG_IMAGE},
        {"property": "og:image:width", "content": "1200"},
        {"property": "og:image:height", "content": "630"},
        {"name": "twitter:card", "content": "summary_large_image"},
        {"name": "twitter:title", "content": page_title},
        {"name": "twitter:description", "content": _OG_DESCRIPTION},
        {"name": "twitter:image", "content": _OG_IMAGE},
        {"name": "description", "content": _OG_DESCRIPTION},
    ]


app = rx.App(
    theme=rx.theme(
        appearance="dark",
        has_background=False,
        radius="large",
        accent_color="iris",
        scaling="100%",
    )
)

app.add_page(
    home,
    route="/",
    title="BirdML — Identify 525 bird species with AI",
    meta=_link_preview_meta("BirdML — Identify 525 bird species with AI"),
)
app.add_page(
    about,
    route="/about",
    title="About — BirdML",
    meta=_link_preview_meta("About — BirdML"),
)
app.add_page(
    catalogue,
    route="/species",
    title="Species — BirdML",
    meta=_link_preview_meta("Species — BirdML"),
)
